### ISSUE TITLE
Sign-up 

### ISSUE THREAD

**Issue by seonghyeoncho** [SSTOF/SSTOF-Frontend#6]
Sign-up에서 이메일만 입력하고 엔터를 누르면 '이메일을 입력해주세요'가 나오고, 계속 엔터를 치면 화면에 알림이 쌓임

**Comment by sangwoo-98** [comment]
알림이 쌓이는 이유는 이메일이 없기 때문!
엔터 치면 이메일 필드 value가 다 비워지기 때문입니다.

알림이 쌓이는건 문제가 맞아서 해결했습니당.
#5  참고~
